### ISSUE TITLE
工程以外的目录下不支持导入子目录 xf_collect 的操作

### ISSUE THREAD

**Issue by dotdotchan** [x-eks-fusion/xf_build#7]
在工程以外的目录下不支持导入子目录 xf_collect 的操作
如 xfusion/xf_wal 的 xf_collect 中导入 xf_ble 下的 xf_collect
![image](https://github.com/user-attachments/assets/a8cfba28-29f4-4971-89f0-f5f5f43d28f8)
报错如下:（关键部分: 16:25:01: 预编译错误: No module named 'xf_ble'）
![image](https://github.com/user-attachments/assets/fa461d48-08ba-4f39-aa75-a8fae21b1b1c)

**Comment by geekheart** [comment]
0.4.1 已经支持该功能。感谢提交 issue
